spring:
  application:
    name: engraver-integration-service
  main:
    web-application-type: none

kafka:
  bootstrap-address: ${KAFKA_BOOTSTRAP_ADDRESS:localhost:29092}
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:${kafka.bootstrap-address}}
  group-id: ${KAFKA_GROUP_ID:engraver-integration-service}
  trusted-packages: ${KAFKA_TRUSTED_PACKAGES:org.unisg.ftengrave.engraverintegrationservice}
  topic:
    auto-create: ${KAFKA_TOPIC_AUTO_CREATE:true}
    bridge-target: ${KAFKA_TOPIC_BRIDGE_TARGET:${kafka.topic.engraver}}
    engraver: ${KAFKA_TOPIC_ENGRAVER:engraver}

mqtt:
  bridge:
    enabled: ${MQTT_BRIDGE_ENABLED:true}
  broker:
    url: ${MQTT_BROKER_URL:tcp://localhost:1883}
  topic: ${MQTT_TOPIC:FTFactory/OV_1}
  client-id: ${MQTT_CLIENT_ID:engraver-integration-service}
  username: ${MQTT_USERNAME:}
  password: ${MQTT_PASSWORD:}

engraver:
  protocol: ${ENGRAVER_PROTOCOL:http}
  host: ${ENGRAVER_HOST:localhost}
  port: ${ENGRAVER_PORT:8081}
  run-path: ${ENGRAVER_RUN_PATH:/ov/burn}
  machine: ${ENGRAVER_MACHINE:ov_1}
