server:
  port: 8103

spring:
  application:
    name: intake-service
  datasource:
    url: jdbc:h2:file:./data/camunda-h2-database

kafka:
  bootstrap-address: ${KAFKA_BOOTSTRAP_ADDRESS:localhost:29092,localhost:29094,localhost:29096}
  group-id: ${KAFKA_GROUP_ID:intake-service}
  trusted-packages: ${KAFKA_TRUSTED_PACKAGES:org.unisg.ftengrave.intakeservice}
  consumer:
    concurrency: ${KAFKA_CONSUMER_CONCURRENCY:3}
  topic:
    auto-create: ${KAFKA_TOPIC_AUTO_CREATE:true}
    replication-factor: ${KAFKA_TOPIC_REPLICATION_FACTOR:3}
    default-partitions: ${KAFKA_TOPIC_DEFAULT_PARTITIONS:1}
    stage-orchestration: ${KAFKA_TOPIC_STAGE_ORCHESTRATION:stage-orchestration}
    stage-orchestration-partitions: ${KAFKA_TOPIC_STAGE_ORCHESTRATION_PARTITIONS:3}
    machine-orchestration: ${KAFKA_TOPIC_MACHINE_ORCHESTRATION:machine-orchestration}
    machine-orchestration-partitions: ${KAFKA_TOPIC_MACHINE_ORCHESTRATION_PARTITIONS:3}
    user-task-management: ${KAFKA_TOPIC_USER_TASK_MANAGEMENT:user-task-management}
    vacuum-gripper: ${KAFKA_TOPIC_VACUUM_GRIPPER:vacuum-gripper}
    engraver: ${KAFKA_TOPIC_ENGRAVER:engraver}

integration:
  vacuum-gripper:
    command-types:
      move-to-engraver: ${VACUUM_GRIPPER_COMMAND_TYPE_MOVE_TO_ENGRAVER:move-item-from-input-to-engraver-command}

camunda.bpm:
  admin-user:
    id: demo
    password: demo
  filter.create: All Tasks
  generic-properties:
    properties:
      historyTimeToLive: P1D
