spring.application.name=frontend-springboot-service
server.port=8081

# Kafka
spring.kafka.bootstrap-servers=localhost:29092
app.kafka.topic.order-events=${APP_KAFKA_TOPIC_ORDER_EVENTS:order-events}
app.kafka.topic.order-created=${APP_KAFKA_TOPIC_ORDER_CREATED:order-created}
