spring.application.name=frontend-springboot-service
server.port=8081

# Kafka
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092,localhost:29094,localhost:29096}
app.kafka.topic.order-events=${APP_KAFKA_TOPIC_ORDER_EVENTS:order-events}
app.kafka.topic.order-created=${APP_KAFKA_TOPIC_ORDER_CREATED:order-created}
app.kafka.topic.machine-orchestration=${APP_KAFKA_TOPIC_MACHINE_ORCHESTRATION:machine-orchestration}
app.kafka.topic.replication-factor=${APP_KAFKA_TOPIC_REPLICATION_FACTOR:3}
app.kafka.topic.order-events-partitions=${APP_KAFKA_TOPIC_ORDER_EVENTS_PARTITIONS:3}
app.kafka.topic.order-created-partitions=${APP_KAFKA_TOPIC_ORDER_CREATED_PARTITIONS:3}

# Kafka consumer
app.kafka.consumer.group-id=${APP_KAFKA_CONSUMER_GROUP_ID:frontend-service-group}
