server:
  port: 8101

spring:
  application:
    name: order-orchestrator
  datasource:
    url: jdbc:h2:file:./data/camunda-h2-database

kafka:
  bootstrap-address: ${KAFKA_BOOTSTRAP_ADDRESS:localhost:29092,localhost:29094,localhost:29096}
  group-id: ${KAFKA_GROUP_ID:order-orchestrator}
  trusted-packages: ${KAFKA_TRUSTED_PACKAGES:org.unisg.ftengrave.orderorchestrator.adapter.out.kafka.dto,org.unisg.ftengrave.orderorchestrator.adapter.in.kafka.dto}
  consumer:
    concurrency: ${KAFKA_CONSUMER_CONCURRENCY:3}
  topic:
    auto-create: ${KAFKA_TOPIC_AUTO_CREATE:true}
    replication-factor: ${KAFKA_TOPIC_REPLICATION_FACTOR:3}
    order-created: ${KAFKA_TOPIC_ORDER_CREATED:order-created}
    order-created-partitions: ${KAFKA_TOPIC_ORDER_CREATED_PARTITIONS:3}
    stage-orchestration: ${KAFKA_TOPIC_STAGE_ORCHESTRATION:stage-orchestration}
    stage-orchestration-partitions: ${KAFKA_TOPIC_STAGE_ORCHESTRATION_PARTITIONS:3}
    machine-orchestration: ${KAFKA_TOPIC_MACHINE_ORCHESTRATION:machine-orchestration}
    machine-orchestration-partitions: ${KAFKA_TOPIC_MACHINE_ORCHESTRATION_PARTITIONS:3}

camunda.bpm:
  admin-user:
    id: demo
    password: demo
  filter.create: All Tasks
  generic-properties:
    properties:
      historyTimeToLive: P1D
