server:
  port: 8101

spring:
  application:
    name: order-orchestrator
  datasource:
    url: jdbc:h2:file:./data/camunda-h2-database

kafka:
  bootstrap-address: ${KAFKA_BOOTSTRAP_ADDRESS:localhost:29092}
  group-id: ${KAFKA_GROUP_ID:order-orchestrator}
  trusted-packages: ${KAFKA_TRUSTED_PACKAGES:org.unisg.ftengrave.orderorchestrator.adapter.out.kafka.dto,org.unisg.ftengrave.orderorchestrator.adapter.in.kafka.dto}
  topic:
    auto-create: ${KAFKA_TOPIC_AUTO_CREATE:true}
    stage-orchestration: ${KAFKA_TOPIC_STAGE_ORCHESTRATION:stage-orchestration}
    machine-orchestration: ${KAFKA_TOPIC_MACHINE_ORCHESTRATION:machine-orchestration}

camunda.bpm:
  admin-user:
    id: demo
    password: demo
  filter.create: All Tasks
  generic-properties:
    properties:
      historyTimeToLive: P1D
