services:
  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_HOST://:29092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # --- Used for testing Only --- (if there is extra time make these build conditionally)
  mqtt-broker:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro

  factory-simulator:
    build:
      context: ../factory-simulator
      dockerfile: Dockerfile
    depends_on:
      - mqtt-broker
    ports:
      - "8081:8081"
    environment:
      FACTORY_MQTT_BROKER_URL: tcp://mqtt-broker:1883
      FACTORY_MQTT_TOPIC: FTFactory/SM_1
      FACTORY_MQTT_PUBLISH_INTERVAL: 2s
  # --- END Used for testing Only ---

  demo-service:
    build:
      context: ../demo-service
      dockerfile: Dockerfile
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_BOOTSTRAP_ADDRESS: kafka:9092
      SPRING_DATASOURCE_URL: jdbc:h2:file:/app/data/camunda-h2-database
    volumes:
      - demo-service-data:/app/data

  qc-service:
    build:
      context: ../qc-service
      dockerfile: Dockerfile
    ports:
      - "8100:8100"
    environment:
      KAFKA_BOOTSTRAP_ADDRESS: kafka:9092
      KAFKA_TOPIC_SORTING_MACHINE: sorting-machine
      SPRING_DATASOURCE_URL: jdbc:h2:file:/app/data/camunda-h2-database
    volumes:
      - qc-service-data:/app/data

  sorter-integration-service:
    build:
      context: ..
      dockerfile: sorter-integration-service/Dockerfile
    depends_on:
      - kafka
      - mqtt-broker
      - factory-simulator
    env_file:
      - ./.env.mqtt.local
    environment:
      KAFKA_BOOTSTRAP_ADDRESS: kafka:9092
      KAFKA_TOPIC_SORTING_MACHINE: sorting-machine
      MQTT_BROKER_URL: tcp://192.168.0.21:1883 # Production
      # MQTT_BROKER_URL: tcp://mqtt-broker:1883 # Simulation
      SORTER_HOST: 192.168.0.21 # Production
      # SORTER_HOST: factory-simulator # Simulation
      SORTER_PORT: 5000 # Production
      # SORTER_PORT: 8081 # Simulation

volumes:
  demo-service-data:
  qc-service-data:
