name: air-tag-factory

services:
  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_HOST://:29092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  demo-service:
    build:
      context: ../demo-service
      dockerfile: Dockerfile
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_BOOTSTRAP_ADDRESS: kafka:9092
      SPRING_DATASOURCE_URL: jdbc:h2:file:/app/data/camunda-h2-database
    volumes:
      - demo-service-data:/app/data

  frontend-springboot-service:
    build:
      context: ../frontend-springboot-service
      dockerfile: Dockerfile
    depends_on:
      - kafka
    ports:
      - "8081:8081"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  frontend-service:
    build:
      context: ../frontend-service
      dockerfile: Dockerfile
    depends_on:
      - frontend-springboot-service
    ports:
      - "3000:80"

volumes:
  demo-service-data:
