name: air-tag-factory

x-kafka-env: &kafka-env
  KAFKA_BOOTSTRAP_ADDRESS: ${KAFKA_BOOTSTRAP_ADDRESS:-kafka:9092,kafka-2:9092,kafka-3:9092}

x-kafka-common-env: &kafka-common-env
  CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
  KAFKA_PROCESS_ROLES: broker,controller
  KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
  KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093,2@kafka-2:9093,3@kafka-3:9093
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
  KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
  KAFKA_DEFAULT_REPLICATION_FACTOR: 3
  KAFKA_MIN_INSYNC_REPLICAS: 2
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
  KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2

x-mqtt-env: &mqtt-env
  MQTT_BROKER_URL: ${MQTT_BROKER_URL}

x-sorter-endpoint: &sorter-endpoint
  SORTER_HOST: ${SORTER_HOST}
  SORTER_PORT: ${SORTER_PORT}

x-vacuum-gripper-endpoint: &vacuum-gripper-endpoint
  VACUUM_GRIPPER_HOST: ${VACUUM_GRIPPER_HOST}
  VACUUM_GRIPPER_PORT: ${VACUUM_GRIPPER_PORT}

x-engraver-endpoint: &engraver-endpoint
  ENGRAVER_HOST: ${ENGRAVER_HOST}
  ENGRAVER_PORT: ${ENGRAVER_PORT}

x-polishing-machine-endpoint: &polishing-machine-endpoint
  POLISHING_MACHINE_HOST: ${POLISHING_MACHINE_HOST}
  POLISHING_MACHINE_PORT: ${POLISHING_MACHINE_PORT}

x-workstation-transport-endpoint: &workstation-transport-endpoint
  WORKSTATION_TRANSPORT_HOST: ${WORKSTATION_TRANSPORT_HOST}
  WORKSTATION_TRANSPORT_PORT: ${WORKSTATION_TRANSPORT_PORT}

services:
  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "29092:29092"
    environment:
      <<: *kafka-common-env
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: INTERNAL://:9092,EXTERNAL://:29092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:29092

  kafka-2:
    image: confluentinc/cp-kafka:latest
    ports:
      - "29094:29092"
    environment:
      <<: *kafka-common-env
      KAFKA_NODE_ID: 2
      KAFKA_LISTENERS: INTERNAL://:9092,EXTERNAL://:29092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-2:9092,EXTERNAL://localhost:29094

  kafka-3:
    image: confluentinc/cp-kafka:latest
    ports:
      - "29096:29092"
    environment:
      <<: *kafka-common-env
      KAFKA_NODE_ID: 3
      KAFKA_LISTENERS: INTERNAL://:9092,EXTERNAL://:29092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-3:9092,EXTERNAL://localhost:29096

  qc-service:
    build:
      context: ..
      dockerfile: qc-service/Dockerfile
    depends_on:
      - kafka
      - kafka-2
      - kafka-3
    ports:
      - "8100:8100"
    environment:
      <<: *kafka-env
      KAFKA_TOPIC_STAGE_ORCHESTRATION: stage-orchestration
      KAFKA_TOPIC_MACHINE_ORCHESTRATION: machine-orchestration
      KAFKA_TOPIC_SORTING_MACHINE: sorting-machine
      SPRING_DATASOURCE_URL: jdbc:h2:file:/app/data/camunda-h2-database
    volumes:
      - qc-service-data:/app/data

  order-orchestrator:
    build:
      context: ..
      dockerfile: order-orchestrator/Dockerfile
    depends_on:
      - kafka
      - kafka-2
      - kafka-3
    ports:
      - "8101:8101"
    environment:
      <<: *kafka-env
      KAFKA_TOPIC_ORDER_CREATED: order-created
      KAFKA_TOPIC_STAGE_ORCHESTRATION: stage-orchestration
      KAFKA_TOPIC_MACHINE_ORCHESTRATION: machine-orchestration
      SPRING_DATASOURCE_URL: jdbc:h2:file:/app/data/camunda-h2-database
    volumes:
      - order-orchestrator-data:/app/data

  intake-service:
    build:
      context: ..
      dockerfile: intake-service/Dockerfile
    depends_on:
      - kafka
      - kafka-2
      - kafka-3
    ports:
      - "8103:8103"
    environment:
      <<: *kafka-env
      KAFKA_TOPIC_STAGE_ORCHESTRATION: stage-orchestration
      KAFKA_TOPIC_MACHINE_ORCHESTRATION: machine-orchestration
      KAFKA_TOPIC_USER_TASK_MANAGEMENT: user-task-management
      KAFKA_TOPIC_VACUUM_GRIPPER: vacuum-gripper
      KAFKA_TOPIC_ENGRAVER: engraver
      SPRING_DATASOURCE_URL: jdbc:h2:file:/app/data/camunda-h2-database
    volumes:
      - intake-service-data:/app/data

  manufacturing-service:
    build:
      context: ..
      dockerfile: manufacturing-service/Dockerfile
    depends_on:
      - kafka
      - kafka-2
      - kafka-3
    ports:
      - "8104:8104"
    environment:
      <<: *kafka-env
      KAFKA_TOPIC_STAGE_ORCHESTRATION: stage-orchestration
      KAFKA_TOPIC_MACHINE_ORCHESTRATION: machine-orchestration
      KAFKA_TOPIC_ENGRAVER: engraver
      KAFKA_TOPIC_WORKSTATION_TRANSPORT: workstation-transport
      KAFKA_TOPIC_POLISHING_MACHINE: polishing-machine
      SPRING_DATASOURCE_URL: jdbc:h2:file:/app/data/camunda-h2-database
    volumes:
      - manufacturing-service-data:/app/data

  kafka-inspector-service:
    build:
      context: ..
      dockerfile: kafka-inspector-service/Dockerfile
    depends_on:
      - kafka
      - kafka-2
      - kafka-3
    ports:
      - "8102:8102"
    environment:
      <<: *kafka-env
      KAFKA_TOPIC_SUBSCRIBE: sorting-machine
      KAFKA_TOPIC_PUBLISH: sorting-machine
      KAFKA_TOPIC_COMMAND_PUBLISH: sorting-machine

  sorter-integration-service:
    build:
      context: ..
      dockerfile: sorter-integration-service/Dockerfile
    depends_on:
      - kafka
      - kafka-2
      - kafka-3
    env_file:
      - ./.env.mqtt.local
    environment:
      <<: [*kafka-env, *mqtt-env, *sorter-endpoint]
      KAFKA_TOPIC_SORTING_MACHINE: sorting-machine
      MQTT_TOPIC: FTFactory/SM_1

  vacuum-gripper-integration-service:
    build:
      context: ..
      dockerfile: vacuum-gripper-integration-service/Dockerfile
    depends_on:
      - kafka
      - kafka-2
      - kafka-3
    env_file:
      - ./.env.mqtt.local
    environment:
      <<: [*kafka-env, *mqtt-env, *vacuum-gripper-endpoint]
      KAFKA_TOPIC_VACUUM_GRIPPER: vacuum-gripper
      MQTT_TOPIC: FTFactory/VGR_1

  engraver-integration-service:
    build:
      context: ..
      dockerfile: engraver-integration-service/Dockerfile
    depends_on:
      - kafka
      - kafka-2
      - kafka-3
    env_file:
      - ./.env.mqtt.local
    environment:
      <<: [*kafka-env, *mqtt-env, *engraver-endpoint]
      KAFKA_TOPIC_ENGRAVER: engraver
      MQTT_TOPIC: FTFactory/OV_1

  polishing-machine-integration-service:
    build:
      context: ..
      dockerfile: polishing-machine-integration-service/Dockerfile
    depends_on:
      - kafka
      - kafka-2
      - kafka-3
    env_file:
      - ./.env.mqtt.local
    environment:
      <<: [*kafka-env, *mqtt-env, *polishing-machine-endpoint]
      KAFKA_TOPIC_POLISHING_MACHINE: polishing-machine
      MQTT_TOPIC: FTFactory/MM_1

  workstation-transport-integration-service:
    build:
      context: ..
      dockerfile: workstation-transport-integration-service/Dockerfile
    depends_on:
      - kafka
      - kafka-2
      - kafka-3
    env_file:
      - ./.env.mqtt.local
    environment:
      <<: [*kafka-env, *mqtt-env, *workstation-transport-endpoint]
      KAFKA_TOPIC_WORKSTATION_TRANSPORT: workstation-transport
      MQTT_TOPIC: FTFactory/WT_1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
      - kafka-2
      - kafka-3
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: ${KAFKA_BOOTSTRAP_ADDRESS:-kafka:9092,kafka-2:9092,kafka-3:9092}

  frontend-springboot-service:
    build:
      context: ../frontend-springboot-service
      dockerfile: Dockerfile
    depends_on:
      - kafka
      - kafka-2
      - kafka-3
    ports:
      - "8082:8081"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_ADDRESS:-kafka:9092,kafka-2:9092,kafka-3:9092}

  frontend-service:
    build:
      context: ../frontend-service
      dockerfile: Dockerfile
    depends_on:
      - frontend-springboot-service
    ports:
      - "3000:80"

volumes:
  qc-service-data:
  order-orchestrator-data:
  intake-service-data:
  manufacturing-service-data:
