server:
  port: 8100

spring:
  application:
    name: qc-service
  datasource:
    url: jdbc:h2:file:./data/camunda-h2-database

kafka:
  bootstrap-address: ${KAFKA_BOOTSTRAP_ADDRESS:localhost:9092}
  trusted-packages: ${KAFKA_TRUSTED_PACKAGES:org.unisg.ftengrave.qcservice.adapter.out.kafka.dto}
  topic:
    sorting-machine: ${KAFKA_TOPIC_SORTING_MACHINE:sorting-machine}

integration:
  sorter:
    event-types:
      rejection: ${SORTER_EVENT_TYPE_REJECTION:sort-to-reject}
      retry: ${SORTER_EVENT_TYPE_RETRY:sort-to-retry}
      shipping: ${SORTER_EVENT_TYPE_SHIPPING:sort-to-shipping}

camunda.bpm:
  admin-user:
    id: demo
    password: demo
  filter.create: All Tasks
  generic-properties:
    properties:
      historyTimeToLive: P1D

mqtt:
  broker:
    url: tcp://192.168.0.21:1883
  topic: FTFactory/SM_1

kafka:
  topic: sorting-machine
  bootstrap-address: localhost:29092