server:
  port: 8100

spring:
  application:
    name: qc-service
  datasource:
    url: jdbc:h2:file:./data/camunda-h2-database

camunda.bpm:
  admin-user:
    id: demo
    password: demo
  filter.create: All Tasks
  generic-properties:
    properties:
      historyTimeToLive: P1D

mqtt:
  broker:
    url: tcp://192.168.0.21:1883
  topic: FTFactory/SM_1

kafka:
  topic: sorting-machine
  bootstrap-address: localhost:29092