spring:
  application:
    name: workstation-transport-integration-service
  main:
    web-application-type: none

kafka:
  bootstrap-address: ${KAFKA_BOOTSTRAP_ADDRESS:localhost:29092,localhost:29094,localhost:29096}
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:${kafka.bootstrap-address}}
  group-id: ${KAFKA_GROUP_ID:workstation-transport-integration-service}
  trusted-packages: ${KAFKA_TRUSTED_PACKAGES:org.unisg.ftengrave.workstationtransportintegrationservice}
  topic:
    auto-create: ${KAFKA_TOPIC_AUTO_CREATE:true}
    replication-factor: ${KAFKA_TOPIC_REPLICATION_FACTOR:3}
    default-partitions: ${KAFKA_TOPIC_DEFAULT_PARTITIONS:1}
    workstation-transport-command: ${KAFKA_TOPIC_WORKSTATION_TRANSPORT_COMMAND:workstation-transport-commands}
    workstation-transport-event: ${KAFKA_TOPIC_WORKSTATION_TRANSPORT_EVENT:workstation-transport-events}
    workstation-transport: ${kafka.topic.workstation-transport-event}
    bridge-target: ${KAFKA_TOPIC_BRIDGE_TARGET:${kafka.topic.workstation-transport-event}}

mqtt:
  bridge:
    enabled: ${MQTT_BRIDGE_ENABLED:true}
  broker:
    url: ${MQTT_BROKER_URL:tcp://localhost:1883}
  topic: ${MQTT_TOPIC:FTFactory/WT_1}
  client-id: ${MQTT_CLIENT_ID:workstation-transport-integration-service}
  username: ${MQTT_USERNAME:}
  password: ${MQTT_PASSWORD:}

workstation-transport:
  protocol: ${WORKSTATION_TRANSPORT_PROTOCOL:http}
  host: ${WORKSTATION_TRANSPORT_HOST:localhost}
  port: ${WORKSTATION_TRANSPORT_PORT:8081}
  transport-path: ${WORKSTATION_TRANSPORT_PATH:/wt/pick_up_and_transport}
  machine: ${WORKSTATION_TRANSPORT_MACHINE:wt_1}
  start: ${WORKSTATION_TRANSPORT_START:oven}
  end: ${WORKSTATION_TRANSPORT_END:milling_machine}
