server:
  port: 8102

spring:
  application:
    name: kafka-inspector-service

kafka:
  bootstrap-address: ${KAFKA_BOOTSTRAP_ADDRESS:localhost:29092}
  group-id: ${KAFKA_GROUP_ID:kafka-inspector-service}
  trusted-packages: ${KAFKA_TRUSTED_PACKAGES:*}
  topic:
    subscribe: ${KAFKA_TOPIC_SUBSCRIBE:stage-orchestration}
    publish: ${KAFKA_TOPIC_PUBLISH:machine-orchestration}

