FROM maven:3.9.9-eclipse-temurin-21 AS builder

WORKDIR /build

COPY pom.xml .
COPY src ./src

RUN mvn -DskipTests package

FROM eclipse-temurin:21-jre

WORKDIR /app

COPY --from=builder /build/target/order-orchestrator.jar app.jar

EXPOSE 8101

ENTRYPOINT ["java", "-jar", "/app/app.jar"]
